# This is a basic workflow to help you get started with Actions

name: CIJavaXXI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  #Job 01
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world! - Build
        
               
  depdev:
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: webdev.123milhas.com
    needs: build
    steps:
      - name: Run a one-line script
        run: echo Hello, world! - Dev
        

  dephmg:
    runs-on: ubuntu-latest
    environment:
      name: hmg
      url: webhmg.123milhas.com
    needs: depdev
    steps:
      - name: Run a one-line script
        run: echo Hello, world! - HMG    
   
   
  depprod:
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: 123milhas.com
    needs: dephmg
    steps:
      - name: Run a one-line script
        run: echo Hello, world! - PROD
        
        
